version: '3.8'
services:
    # database:
    #     container_name: database
    #     image: mysql:8.0
    #     command: --default-authentication-plugin=mysql_native_password
    #     environment:
    #       MYSQL_ROOT_PASSWORD: illuali
    #       MYSQL_DATABASE: symfony_docker
    #       MYSQL_USER: admin
    #       MYSQL_PASSWORD: illuali
    #     ports:
    #       - '4306:3306'
    #     volumes:
    #       - ./mysql:/var/lib/mysql
    postgres:
        image: postgres:12.4-alpine
        restart: on-failure
        environment:
            POSTGRES_DB: ${PGSQL_DB_NAME}
            POSTGRES_USER: ${PGSQL_DB_USER}
            POSTGRES_PASSWORD: ${PGSQL_DB_PASSWORD}
            PGDATA: /var/lib/postgresql/data
        volumes:
            - ./db-data:/var/lib/postgresql/data:rw
        ports:
            - "5432:5432"
        networks:
            - symfony
    php:
        container_name: php_postgres
        restart: on-failure
        build:
          context: ./php
          args:
              GITHUB_EMAIL: ${GITHUB_EMAIL}
              GITHUB_NAME: ${GITHUB_NAME}
        ports:
          - '1000:8000'
        volumes:
          - ./../apps:/var/www/symfony_docker
        depends_on:
          - postgres
          # - database
        networks:
            - symfony
    nginx:
        container_name: nginx_postgres
        image: nginx:stable-alpine
        ports:
          - '90:80'
        volumes:
          - ./../apps:/var/www/symfony_docker
          - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
          - php
          - postgres
          # - database
        networks:
            - symfony
networks:
    symfony: